version = 0.1
[default.global.parameters]
stack_name = "redis-api-caching"

[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18ed0j5xol14m"
s3_prefix = "redis-api-caching"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"



